### ISSUE TITLE
deploy_contract_and_test.py gives this error 

### ISSUE THREAD

**Issue by hmandora** [JungWinter/file-on-blockchain#1]
python3 deploy_contract_and_test.py 

Traceback (most recent call last):
  File "deploy_contract_and_test.py", line 32, in <module>
    compiled_sol = compile_source(contract_source_code)
  File "/usr/local/lib/python3.6/dist-packages/solc/main.py", line 108, in compile_source
    stdoutdata, stderrdata, command, proc = solc_wrapper(**compiler_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/solc/utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/solc/wrapper.py", line 159, in solc_wrapper
    stderr=subprocess.PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'solc': 'solc'

**Comment by hmandora** [comment]
Above issue resolved. Now I am getting below compilation error.

Vostro-1450:~/file-on-blockchain-master/example$ python3 deploy_contract_and_test.py solc --combined-json bin

Traceback (most recent call last):
  File "deploy_contract_and_test.py", line 32, in <module>
    compiled_sol = compile_source(contract_source_code)
  File "/usr/local/lib/python3.6/dist-packages/solc/main.py", line 108, in compile_source
    stdoutdata, stderrdata, command, proc = solc_wrapper(**compiler_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/solc/utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/solc/wrapper.py", line 169, in solc_wrapper
    stderr_data=stderrdata,
solc.exceptions.SolcError: An error occurred during execution
> command: `solc --combined-json abi,asm,ast,bin,bin-runtime,clone-bin,devdoc,interface,opcodes,userdoc`
> return code: `1`
> stderr:

> stdout:
Invalid option to --combined-json: clone-bin
